services:
  nodejs:
    container_name: webhook-nodejs
    build: 
      context : ./nodejs
    expose:
      - "3000"
    volumes:
      - ./nodejs:/app
      - /app/node_modules
    restart: always

  nginx:
    container_name: webhook-nginx
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs
    volumes:
      - ./frontend/dist:/app
    restart: always